### ISSUE TITLE
Linking GPS data to video frames

### ISSUE THREAD

**Issue by haimat** [alexis-mignon/pygpmf#3]
I am using `pygmf` to extract GPS data from my video file. That works fine, I can get that GPS data as XML file. However, I don't see any link from that XML data to the frames of video. How can I get the GPS data of a single frame in the GoPro video?

**Comment by Martin91** [comment]
Hi @haimat, have you implemented any solution to do this? I also need to extract specific frames according to the original GPS data

**Comment by Martin91** [comment]
After reading the official document here https://github.com/gopro/gpmf-parser#gpmf-timing-and-clocks
I am aware that there is no accurate matching between frames and GPS samples because the sample rate of the video is different from one of GPS, so we need to calculate the time elapsed and determine the current frame index based on the sample rate of the video.

**Comment by haimat** [comment]
> After reading the official document here https://github.com/gopro/gpmf-parser#gpmf-timing-and-clocks I am aware that there is no accurate matching between frames and GPS samples because the sample rate of the video is different from one of GPS, so we need to calculate the time elapsed and determine the current frame index based on the sample rate of the video.

Exactly, this is what we ended up doing :)

**Comment by jakobsnl** [comment]
@haimat  would you mind sharing your solution? I am also searching for the distance bewteen 1st frame and 1st gps record, as this interval varies a lot and makes it hard to sync both information. 

Would appreciate your help a lot, many thank in advance in case this works :)

**Comment by haimat** [comment]
@jakobsnl To be frank, we don't use this solution any more. It turned out this was not really what we were looking for. We ended with the [GoPro Telemetry](https://github.com/JuanIrache/gopro-telemetry) package, which is much closer to what we need, and works quite well. It's not Python, but very easy to call from a Python program as a spawned process. HTH!

**Comment by jakobsnl** [comment]
@haimat  Do you have any experience you can share regarding the 'cts' attribute that is part of the data returned by GoPro Telemetry. Its supposed to quantify the distance between the first e.g. GPS timestamp and the first video frame? Or alternatively, is there a different way to obtain the distance of the first GPS timestamp to the first image frame in milliseconds accuracy? Many thanks in advance! Jakob

**Comment by haimat** [comment]
@jakobsnl I don't have the code here, but AFAIR the `cts` value is simply the timestamp related to that frame. So you can simply compare two such timestamps to calculate the delta between them.
